### PR TITLE
Refactor - Parent the Cameras to the OxrTrackingRoot

### PR DESCRIPTION
**Pull request by Schmarni-Dev**

### CODE REVIEW

**Comment by ForTehLose** [comment]
Looks good to me, Ill try to test on windows steamvr tonight. Can anyone test on android or linux?

**Comment by MalekiRe** [comment]
Wasn't able to test the code ( lack of vr headset ) but the code itself makes sense to me!

**Review by MalekiRe — APPROVED** [review]

**Comment by 0xtito** [comment]
> Looks good to me, Ill try to test on windows steamvr tonight. Can anyone test on android or linux?

just tested with mac + android, no problems here! (aside from the slight adjustment I made here #101)

**Comment by ForTehLose** [comment]
tested on windows and steamvr with a bigscreen beyond, worked great.

**Pull request merged**
